### ISSUE TITLE
sugarss

### ISSUE THREAD

**Issue by comerc** [juliancwirko/meteor-postcss-test#1]
Please help me - [test](https://github.com/comerc/meteor-postcss-test) from [this instruction](https://forums.meteor.com/t/is-there-any-way-to-use-both-postcss-and-css-modules-in-my-project/21506/3) does not work.

**Comment by juliancwirko** [comment]
Hi, you need to use standard `.css` extension not `.sss` This is because the Meteor build plugin searches for .css files in that case. Everything else should work.
